image: local-registry.inner.buaaoo.top/image-dev/java:8u201

stages:
  - build
  - test

before_script:
  - java -version
  - javac -version
  - mvn -v

mvn_build:
  stage: build
  script:
    - echo "Build Project"
    - mvn compile
  artifacts:
    paths:
    - target

mvn_test:
  stage: test
  dependencies:
    - mvn_build
  script:
    - echo "Run JUnit4"
    - mvn test
    - echo "Code coverage 99%"
  coverage: '/Code coverage \d+/'
